services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=LuaComTil
      - MYSQL_PASSWORD=Senha415
      - MYSQL_DATABASE=bostitter_db
      - MYSQL_ROOT_PASSWORD=Senha415